custom_module.settings:
type: config_object
mapping:
type:
type: string
label: 'Message type'
message:
type: label
label: 'Message text'
langcode:
type: string
label: 'Language code'
env:
type: string
label: 'Env variable'